//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_VELILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_VELILER()
        {
            this.TBL_OGRENCILERR = new HashSet<TBL_OGRENCILERR>();
        }
    
        public int VELIID { get; set; }
        public string VELIANNNE { get; set; }
        public string VELIBABA { get; set; }
        public string VELITEL1 { get; set; }
        public string VELITEL2 { get; set; }
        public string VELIMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_OGRENCILERR> TBL_OGRENCILERR { get; set; }
    }
}
